name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'small-apps-433901' # Your Google Cloud project ID
  REGION: 'us-west1'              # Your region
  SERVICE: 'quick-deploy'          # Your Cloud Run service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/250555830433/locations/global/workloadIdentityPools/github/providers/my-repo' # Workload identity provider

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'

    # Authenticate to Google Cloud using Workload Identity Federation
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: 'github-action@small-apps-433901.iam.gserviceaccount.com'  # The service account to impersonate

    # Configure Docker to use Google Artifact Registry
    - name: 'Docker Auth'
      uses: 'docker/login-action@v3'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.auth_token }}'
        registry: '${{ env.REGION }}-docker.pkg.dev'

    # Build and push the container image to Google Artifact Registry
    - name: 'Build and Push Container'
      run: |
        DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
        docker build --tag "${DOCKER_TAG}" .
        docker push "${DOCKER_TAG}"

    # Deploy the container to Cloud Run
    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: '${{ env.SERVICE }}'
        image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'
        region: '${{ env.REGION }}'
        project_id: '${{ env.PROJECT_ID }}'

    # If required, use the Cloud Run URL output in later steps
    - name: 'Show output'
      run: echo ${{ steps.deploy.outputs.url }}
