name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'  # Updated branch syntax

env:
  PROJECT_ID: 'small-apps-433901'  # Your Google Cloud project ID
  REGION: 'us-west1'  # Your preferred region (us-west1 for Oregon)
  SERVICE: 'quick-deploy'  # Name of your Cloud Run service
  WORKLOAD_IDENTITY_PROVIDER: 'projects/250555830433/locations/global/workloadIdentityPools/github/providers/my-repo'  # Workload Identity Provider

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # Docker authentication and image build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'  # Correct variable name for the token
          registry: '${{ env.REGION }}-docker.pkg.dev'  # Artifact Registry Docker endpoint

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      # Show Cloud Run URL
      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
