name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'small-apps-433901'
  REGION: 'us-west1'
  SERVICE: 'quick-deploy'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step to decode the base64 encoded Service Account Key JSON
      - name: 'Decode and Create Service Account Key JSON'
        run: |
          echo "${{ secrets.QUICK_DEPLOY_BASE64 }}" | base64 --decode > ${{ github.workspace }}/key.json
          gcloud --quiet auth activate-service-account --key-file="${{ github.workspace }}/key.json"

      # Set up Docker authentication for Google Cloud Artifact Registry
      - name: 'Set up Google Cloud authentication for Docker'
        run: |
          gcloud --quiet auth configure-docker ${REGION}-docker.pkg.dev

      # Build and Push Container
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Deploy the Container to Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      # Show Cloud Run URL
      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
